value1 = {
    "objectID": 1,
    "isHighlight": 0,
    "accessionNumber": "1979.486.1",
    "accessionYear": 1979,
    "isPublicDomain": 0,
    "primaryImage": '0',
    "primaryImageSmall": '0',
    "additionalImages": "[]",
    "department": "The American Wing",
    "objectName": "Coin",
    "title": "One-dollar Liberty Head Coin",
    "culture": '0',
    "period": '0.0',
    "dynasty": '0',
    "reign": '0',
    "portfolio": '0',
    "artistRole": "Maker",
    "artistPrefix": '0',
    "artistDisplayName": "James Barton Longacre",
    "artistDisplayBio": "American, Delaware County, Pennsylvania 1794\\u20131869 Philadelphia, Pennsylvania",
    "artistSuffix": '0',
    "artistAlphaSort": "Longacre, James Barton",
    "artistNationality": "American",
    "artistBeginDate": "1794",
    "artistEndDate": "1869",
    "artistGender": '0',
    "artistWikidata_URL": "https://www.wikidata.org/wiki/Q3806459",
    "artistULAN_URL": "http://vocab.getty.edu/page/ulan/500011409",
    "objectDate": "1853",
    "objectBeginDate": "1853",
    "objectEndDate": "1853",
    "medium": "Gold",
    "dimensions": "Dimensions unavailable",
    "measurements": "null",
    "creditLine": "Gift of Heinz L. Stoppelmann, 1979",
    "geographyType": '0',
    "city": '0',
    "state": '0',
    "county": '0',
    "country": '0',
    "region": '0',
    "subregion": '0.0',
    "locale": '0.0',
    "locus": '0.0',
    "excavation": '0.0',
    "river": '0.0',
    "classification": '0.0',
    "rightsAndReproduction": '0.0',
    "linkResource": '0.0',
    "metadataDate": "2021-04-06T04:41:04.967Z",
    "repository": "Metropolitan Museum of Art, New York, NY",
    "objectURL": "https://www.metmuseum.org/art/collection/search/1",
    "tags": "null",
    "objectWikidata_URL": '0',
    "isTimelineWork": 0,
    "GalleryNumber": 0,
    "constituentID": 164292.0,
    "role": "Maker",
    "name": "James Barton Longacre",
    "constituentULAN_URL": "http://vocab.getty.edu/page/ulan/500011409",
    "constituentWikidata_URL": "https://www.wikidata.org/wiki/Q3806459",
    "gender": '0'}

value2 = {
        "objectID": 2,
        "isHighlight": 0,
        "accessionNumber": "1980.264.5",
        "accessionYear": 1980,
        "isPublicDomain": 0,
        "primaryImage": '0',
        "primaryImageSmall": '0',
        "additionalImages": "[]",
        "department": "The American Wing",
        "objectName": "Coin",
        "title": "Ten-dollar Liberty Head Coin",
        "culture": '0',
        "period": '0.0',
        "dynasty": '0',
        "reign": '0',
        "portfolio": '0',
        "artistRole": "Maker",
        "artistPrefix": '0',
        "artistDisplayName": "Christian Gobrecht",
        "artistDisplayBio": "1785\\u20131844",
        "artistSuffix": '0',
        "artistAlphaSort": "Gobrecht, Christian",
        "artistNationality": '0',
        "artistBeginDate": "1785",
        "artistEndDate": "1844",
        "artistGender": '0',
        "artistWikidata_URL": "https://www.wikidata.org/wiki/Q5109648",
        "artistULAN_URL": "http://vocab.getty.edu/page/ulan/500077295",
        "objectDate": "1901",
        "objectBeginDate": "1901",
        "objectEndDate": "1901",
        "medium": "Gold",
        "dimensions": "Dimensions unavailable",
        "measurements": "null",
        "creditLine": "Gift of Heinz L. Stoppelmann, 1980",
        "geographyType": '0',
        "city": '0',
        "state": '0',
        "county": '0',
        "country": '0',
        "region": '0',
        "subregion": '0',
        "locale": '0',
        "locus": '0',
        "excavation": '0',
        "river": '0',
        "classification": '0',
        "rightsAndReproduction": '0',
        "linkResource": '0',
        "metadataDate": "2021-04-06T04:41:04.967Z",
        "repository": "Metropolitan Museum of Art, New York, NY",
        "objectURL": "https://www.metmuseum.org/art/collection/search/2",
        "tags": "null",
        "objectWikidata_URL": '0',
        "isTimelineWork": 0,
        "GalleryNumber": 0,
        "constituentID": 1079.0,
        "role": "Maker",
        "name": "Christian Gobrecht",
        "constituentULAN_URL": "http://vocab.getty.edu/page/ulan/500077295",
        "constituentWikidata_URL": "https://www.wikidata.org/wiki/Q5109648",
        "gender": '0'}

value3 = {
    "objectID": 3,
    "isHighlight": 0,
    "accessionNumber": "67.265.9",
    "accessionYear": "1967",
    "isPublicDomain": 0,
    "primaryImage": 0,
    "primaryImageSmall": 0,
    "additionalImages": "[]",
    "department": "The American Wing",
    "objectName": "Coin",
    "title": "Two-and-a-Half Dollar Coin",
    "culture": 0,
    "period": 0,
    "dynasty": 0,
    "reign": 0,
    "portfolio": 0,
    "artistRole": 0,
    "artistPrefix": 0,
    "artistDisplayName": 0,
    "artistDisplayBio": 0,
    "artistSuffix": 0,
    "artistAlphaSort": 0,
    "artistNationality": 0,
    "artistBeginDate": 0,
    "artistEndDate": 0,
    "artistGender": 0,
    "artistWikidata_URL": 0,
    "artistULAN_URL": 0,
    "objectDate": "1909\\u201327",
    "objectBeginDate": 1909,
    "objectEndDate": 1927,
    "medium": "Gold",
    "dimensions": "Diam. 11/16 in. (1.7 cm)",
    "measurements": "null",
    "creditLine": "Gift of C. Ruxton Love Jr., 1967",
    "geographyType": 0,
    "city": 0,
    "state": 0,
    "county": 0,
    "country": 0,
    "region": 0,
    "subregion": 0,
    "locale": 0,
    "locus": 0,
    "excavation": 0,
    "river": 0,
    "classification": 0,
    "rightsAndReproduction": 0,
    "linkResource": 0,
    "metadataDate": "2021-04-06T04:41:04.967Z",
    "repository": "Metropolitan Museum of Art, New York, NY",
    "objectURL": "https://www.metmuseum.org/art/collection/search/3",
    "tags": "null",
    "objectWikidata_URL": "",
    "isTimelineWork": 0,
    "GalleryNumber": 0,
    "constituentID": 1079,
    "role": "Maker",
    "error":"programmingerror",
    "name": "Christian Gobrecht",
    "constituentULAN_URL": "http://vocab.getty.edu/page/ulan/500077295",
    "constituentWikidata_URL": "https://www.wikidata.org/wiki/Q5109648",
    "gender": 0}

value4 = {
    "objectID": 15,
    "isHighlight": 0,
    "accessionNumber": "16.74.49",
    "accessionYear": "1916",
    "isPublicDomain": 0,
    "primaryImage": 0,
    "primaryImageSmall": 0,
    "additionalImages": "[]",
    "department": "The American Wing",
    "bug":"programmingerror",
    "objectName": "Coin",
    "title": "Coin, 1/2 Real",
    "culture": "Mexican",
    "period": 0,
    "dynasty": 0,
    "reign": 0,
    "portfolio": 0,
    "artistRole": 0,
    "artistPrefix": 0,
    "artistDisplayName": 0,
    "artistDisplayBio": 0,
    "artistSuffix": 0,
    "artistAlphaSort": 0,
    "artistNationality": 0,
    "artistBeginDate": 0,
    "artistEndDate": 0,
    "artistGender": 0,
    "artistWikidata_URL": 0,
    "artistULAN_URL": 0,
    "objectDate": "1665\\u20131700",
    "objectBeginDate": 1665,
    "objectEndDate": 1700,
    "medium": "Silver",
    "dimensions": "Diam. 1/2 in. (1.3 cm)",
    "measurements": "null",
    "creditLine": "Gift of Mrs. Russell Sage, 1916",
    "geographyType": "Made in",
    "city": 0,
    "state": 0,
    "county": 0,
    "country": "Mexico",
    "region": 0,
    "subregion": 0,
    "locale": 0,
    "locus": 0,
    "excavation": 0,
    "river": 0,
    "classification": 0,
    "rightsAndReproduction": 0,
    "linkResource": 0,
    "metadataDate": "2021-04-06T04:41:04.967Z",
    "repository": "Metropolitan Museum of Art, New York, NY",
    "objectURL": "https://www.metmuseum.org/art/collection/search/15",
    "tags": "null",
    "objectWikidata_URL": 0,
    "isTimelineWork": 0,
    "GalleryNumber": 0,
    "constituentID": 1079,
    "role": "Maker",
    "name": "Christian Gobrecht",
    "constituentULAN_URL": "http://vocab.getty.edu/page/ulan/500077295",
    "constituentWikidata_URL": "https://www.wikidata.org/wiki/Q5109648",
    "gender": 0}

value5 = {
    "objectID": 15,
    "isHighlight": 0,
    "accessionNumber": "16.74.49",
    "accessionYear": "1916",
    "isPublicDomain": 0,
    "primaryImage": 0,
    "primaryImageSmall": 0,
    "additionalImages": "[]",
    "department": "The American Wing",
    "objectName": "Coin",
    "title": "Coin, 1/2 Real",
    "culture": "Mexican",
    "period": 0,
    "dynasty": 0,
    "reign": 0,
    "portfolio": 0,
    "artistRole": 0,
    "artistPrefix": 0,
    "artistDisplayName": 0,
    "artistDisplayBio": 0,
    "artistSuffix": 0,
    "artistAlphaSort": 0,
    "artistNationality": 0,
    "artistBeginDate": 0,
    "artistEndDate": 0,
    "artistGender": 0,
    "artistWikidata_URL": 0,
    "artistULAN_URL": 0,
    "objectDate": "1665\\u20131700",
    "objectBeginDate": 1665,
    "objectEndDate": 1700,
    "medium": "Silver",
    "dimensions": "Diam. 1/2 in. (1.3 cm)",
    "measurements": "null",
    "creditLine": "Gift of Mrs. Russell Sage, 1916",
    "geographyType": "Made in",
    "city": 0,
    "state": 0,
    "county": 0,
    "country": "Mexico",
    "region": 0,
    "subregion": 0,
    "locale": 0,
    "locus": 0,
    "excavation": 0,
    "river": 0,
    "classification": 0,
    "rightsAndReproduction": 0,
    "linkResource": 0,
    "metadataDate": "2021-04-06T04:41:04.967Z",
    "repository": "Metropolitan Museum of Art, New York, NY",
    "objectURL": "https://www.metmuseum.org/art/collection/search/15",
    "tags": "null",
    "objectWikidata_URL": 0,
    "isTimelineWork": 0,
    "ExtraCloumn":"nothing",
    "GalleryNumber": 0,
    "constituentID": 1079,
    "role": "Maker",
    "name": "Christian Gobrecht",
    "constituentULAN_URL": "http://vocab.getty.edu/page/ulan/500077295",
    "constituentWikidata_URL": "https://www.wikidata.org/wiki/Q5109648",
    "gender": 0}

value6 = {
        "objectID": 2,
        "isHighlight": 0,
        "accessionNumber": "1980.264.5",
        "accessionYear": 1980,
        "isPublicDomain": 0,
        "primaryImage": '0',
        "primaryImageSmall": '0',
        "additionalImages": "[]",
        "department": "The updated Wing",
        "objectName": "updated Coin",
        "title": "updated title Ten-dollar Liberty Head Coin",
        "culture": '0',
        "period": '0.0',
        "dynasty": '0',
        "reign": '0',
        "portfolio": '0',
        "artistRole": "Maker",
        "artistPrefix": '0',
        "artistDisplayName": "Christian Gobrecht",
        "artistDisplayBio": "1785u20131844",
        "artistSuffix": '0',
        "artistAlphaSort": "Gobrecht, Christian",
        "artistNationality": '0',
        "artistBeginDate": "1785",
        "artistEndDate": "1844",
        "artistGender": '0',
        "artistWikidata_URL": "https://www.wikidata.org/wiki/Q5109648",
        "artistULAN_URL": "http://vocab.getty.edu/page/ulan/500077295",
        "objectDate": "1901",
        "objectBeginDate": "1901",
        "objectEndDate": "1901",
        "medium": "Gold",
        "dimensions": "Dimensions unavailable",
        "measurements": "null",
        "creditLine": "Gift of Heinz L. Stoppelmann, 1980",
        "geographyType": '0',
        "city": '0',
        "state": '0',
        "county": '0',
        "country": '0',
        "region": '0',
        "subregion": '0',
        "locale": '0',
        "locus": '0',
        "excavation": '0',
        "river": '0',
        "classification": '0',
        "rightsAndReproduction": '0',
        "linkResource": '0',
        "metadataDate": "2021-04-06T04:41:04.967Z",
        "repository": "Metropolitan Museum of Art, New York, NY",
        "objectURL": "https://www.metmuseum.org/art/collection/search/2",
        "tags": "null",
        "objectWikidata_URL": '0',
        "isTimelineWork": 0,
        "GalleryNumber": 0,
        "constituentID": 1079.0,
        "role": "Maker",
        "name": "Christian Gobrecht",
        "constituentULAN_URL": "http://vocab.getty.edu/page/ulan/500077295",
        "constituentWikidata_URL": "https://www.wikidata.org/wiki/Q5109648",
        "gender": '0'}

value7 = {
    "objectID": 9,
    "isHighlight": 0,
    "accessionNumber": "1979.486.1",
    "accessionYear": 1979,
    "isPublicDomain": 0,
    "primaryImage": '0',
    "primaryImageSmall": '0',
    "additionalImages": "[]",
    "department": "The American Wing",
    "objectName": "Coin",
    "title": "One-dollar Liberty Head Coin",
    "culture": '0',
    "period": '0.0',
    "dynasty": '0',
    "reign": '0',
    "portfolio": '0',
    "artistRole": "Maker",
    "artistPrefix": '0',
    "artistDisplayName": "James Barton Longacre",
    "artistDisplayBio": "American, Delaware County, Pennsylvania 1794\\u20131869 Philadelphia, Pennsylvania",
    "artistSuffix": '0',
    "artistAlphaSort": "Longacre, James Barton",
    "artistNationality": "American",
    "artistBeginDate": "1794",
    "artistEndDate": "1869",
    "artistGender": '0',
    "artistWikidata_URL": "https://www.wikidata.org/wiki/Q3806459",
    "artistULAN_URL": "http://vocab.getty.edu/page/ulan/500011409",
    "objectDate": "1853",
    "objectBeginDate": "1853",
    "objectEndDate": "1853",
    "medium": "Gold",
    "dimensions": "Dimensions unavailable",
    "measurements": "null",
    "creditLine": "Gift of Heinz L. Stoppelmann, 1979",
    "geographyType": '0',
    "city": '0',
    "state": '0',
    "county": '0',
    "country": '0',
    "region": '0',
    "subregion": '0.0',
    "locale": '0.0',
    "locus": '0.0',
    "excavation": '0.0',
    "river": '0.0',
    "classification": '0.0',
    "rightsAndReproduction": '0.0',
    "linkResource": '0.0',
    "metadataDate": "2021-04-06T04:41:04.967Z",
    "repository": "Metropolitan Museum of Art, New York, NY",
    "objectURL": "https://www.metmuseum.org/art/collection/search/1",
    "tags": "null",
    "objectWikidata_URL": '0',
    "isTimelineWork": 0,
    "GalleryNumber": 0,
    "constituentID": 164292.0,
    "role": "Maker",
    "name": "James Barton Longacre",
    "constituentULAN_URL": "http://vocab.getty.edu/page/ulan/500011409",
    "constituentWikidata_URL": "https://www.wikidata.org/wiki/Q3806459",
    "gender": '0'}

value8 = {
    "objectID": 100,
    "isHighlight": 0,
    "accessionNumber": "1979.486.1",
    "accessionYear": 1979,
    "isPublicDomain": 0,
    "primaryImage": '0',
    "primaryImageSmall": '0',
    "additionalImages": "[]",
    "department": "The American Wing",
    "objectName": "Coin",
    "title": "One-dollar Liberty Head Coin",
    "culture": '0',
    "period": '0.0',
    "dynasty": '0',
    "reign": '0',
    "portfolio": '0',
    "artistRole": "Maker",
    "artistPrefix": '0',
    "artistDisplayName": "James Barton Longacre",
    "artistDisplayBio": "American, Delaware County, Pennsylvania 1794\\u20131869 Philadelphia, Pennsylvania",
    "artistSuffix": '0',
    "artistAlphaSort": "Longacre, James Barton",
    "artistNationality": "American",
    "artistBeginDate": "1794",
    "artistEndDate": "1869",
    "artistGender": '0',
    "artistWikidata_URL": "https://www.wikidata.org/wiki/Q3806459",
    "artistULAN_URL": "http://vocab.getty.edu/page/ulan/500011409",
    "objectDate": "1853",
    "objectBeginDate": "1853",
    "objectEndDate": "1853",
    "medium": "Gold",
    "dimensions": "Dimensions unavailable",
    "measurements": "null",
    "creditLine": "Gift of Heinz L. Stoppelmann, 1979",
    "geographyType": '0',
    "city": '0',
    "state": '0',
    "county": '0',
    "country": '0',
    "region": '0',
    "subregion": '0.0',
    "locale": '0.0',
    "locus": '0.0',
    "excavation": '0.0',
    "river": '0.0',
    "classification": '0.0',
    "rightsAndReproduction": '0.0',
    "linkResource": '0.0',
    "metadataDate": "2021-04-06T04:41:04.967Z",
    "repository": "Metropolitan Museum of Art, New York, NY",
    "objectURL": "https://www.metmuseum.org/art/collection/search/1",
    "tags": "null",
    "objectWikidata_URL": '0',
    "isTimelineWork": 0,
    "GalleryNumber": 0,
    "constituentID": 164292.0,
    "role": "Maker",
    "name": "James Barton Longacre",
    "constituentULAN_URL": "http://vocab.getty.edu/page/ulan/500011409",
    "constituentWikidata_URL": "https://www.wikidata.org/wiki/Q3806459",
    "gender": '0'}